# Auto-generated by R26-SE-038 Component 3
# Function : calculate_tip
# Valid    : True
# Repairs  : 0
# Run ID   : 47edd392

import pytest
from src.cart import calculate_tip


def test_tc001_normal():
    """Normal case - typical tip calculation."""
    bill = 100
    tip_percent = 15
    expected = 15.0
    result = calculate_tip(bill, tip_percent)
    assert result == expected


def test_tc002_edge_zero():
    """Edge case - zero percent tip."""
    bill = 50
    tip_percent = 0
    expected = 0.0
    result = calculate_tip(bill, tip_percent)
    assert result == expected


def test_tc003_edge_full():
    """Edge case - full 100% tip."""
    bill = 20
    tip_percent = 100
    expected = 20.0
    result = calculate_tip(bill, tip_percent)
    assert result == expected


def test_tc004_exception_negative():
    """Exception case - negative tip percent."""
    bill = 30
    tip_percent = -5
    with pytest.raises(ValueError) as exc_info:
        calculate_tip(bill, tip_percent)
    assert "tip_percent must be between 0 and 100" in str(exc_info.value)