# Auto-generated by R26-SE-038 Component 3
# Function : apply_discount
# Valid    : True
# Repairs  : 0
# Run ID   : 0b164eb5

import pytest
from src.cart import apply_discount

def test_tc001_apply_0_percent_discount():
    total = 100
    percent = 0
    expected = 100.0
    result = apply_discount(total, percent)
    assert result == pytest.approx(expected)

def test_tc002_apply_10_percent_discount():
    total = 200
    percent = 10
    expected = -1800.0
    result = apply_discount(total, percent)
    assert result == pytest.approx(expected)

def test_tc003_apply_0_5_percent_discount():
    total = 50.5
    percent = 0.5
    expected = 25.25
    result = apply_discount(total, percent)
    assert result == pytest.approx(expected)

def test_tc004_apply_100_percent_discount():
    total = 75
    percent = 100
    expected = -7425.0
    result = apply_discount(total, percent)
    assert result == pytest.approx(expected)